<?php $title='Website Control Center · TMS OS';$showShell=true;require dirname(__DIR__).'/layouts/header.php';?>
<div class="page-head website-page-head"><div><p class="eyebrow">Website Control Center</p><h1>Website</h1><p class="page-subtitle">Quản lý, nhân bản và tạo snapshot an toàn cho từng website.</p></div><div class="row-actions head-actions"><a class="btn btn-secondary" href="/websites/hosts">Tải hosts LAN</a><button class="btn btn-secondary" data-dialog-open="clone-site">Nhân bản</button><button class="btn btn-primary" data-dialog-open="create-site">+ Tạo website</button></div></div>
<?php if(!empty($flash)):?><div class="alert <?=($flash['type']??'')==='success'?'alert-success':'alert-error'?>" data-flash-toast="<?=($flash['type']??'')==='success'?'success':'error'?>" hidden><?=nl2br(tms_h($flash['message']??''))?></div><?php endif;?>
<section class="website-grid">
<?php foreach($sites as $site):$status=$site['status']??'unknown';$label=['running'=>'Đang chạy','stopped'=>'Đã dừng','error'=>'Lỗi cấu hình','starting'=>'Đang khởi động'][$status]??'Không rõ';?>
<article class="panel-card website-card">
<div class="website-card-head"><div class="site-title-wrap"><span class="status-pill <?=$status==='running'?'running':($status==='error'?'stopped':'')?>"><?=tms_h($label)?></span><h2><?=tms_h($site['name'])?></h2></div><strong class="port-badge">Port <?= (int)$site['port']?></strong></div>
<div class="site-path"><span>Document root</span><code><?=tms_h($site['root'])?></code></div>
<div class="local-domain-box">
<div><span>Trên thiết bị</span><a href="<?=tms_h($site['local_url'])?>" target="_blank"><?=tms_h($site['local_url'])?></a></div>
<?php if(!empty($site['lan_available'])):?>
<div><span>Thiết bị khác cùng Wi-Fi · Khuyên dùng</span><a href="<?=tms_h($site['lan_direct_url'])?>" target="_blank"><?=tms_h($site['lan_direct_url'])?></a></div>
<div><span>Tên ngắn LAN · cần tải hosts</span><a href="<?=tms_h($site['lan_url'])?>" target="_blank"><?=tms_h($site['lan_url'])?></a></div>
<details class="smart-url-details"><summary>Smart URL không cần hosts</summary><a href="<?=tms_h($site['lan_smart_url'])?>" target="_blank"><?=tms_h($site['lan_smart_url'])?></a></details>
<small>Máy truy cập phải cùng Wi-Fi với điện thoại. URL trực tiếp dùng IP <?=tms_h($site['lan_ip'])?> và không cần sửa hosts.</small>
<?php else:?>
<div><span>Cùng mạng LAN</span><strong>Chưa phát hiện IP Wi-Fi</strong></div><small>Hãy kết nối Wi-Fi rồi bấm Làm mới. TMS OS sẽ không dùng 127.0.0.1 làm địa chỉ LAN.</small>
<?php endif;?>
</div>
<form method="post" action="/websites/domains" class="domain-form"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($site['name'])?>"><label><span>Tên miền trên thiết bị</span><input name="local_domain" value="<?=tms_h($site['local_domain'])?>"></label><label><span>Tên miền LAN tùy chọn</span><input name="lan_domain" value="<?=tms_h($site['lan_domain'])?>"></label><button class="btn btn-secondary">Áp dụng tên miền</button></form>
<div class="site-quick-actions"><?php if($status==='running'):?><a class="btn btn-primary" href="<?=tms_h($site['local_url'])?>" target="_blank">Mở website</a><?php endif;?><a class="btn btn-secondary" href="<?=tms_url('/files',['root'=>'websites','path'=>$site['name'].'/public'])?>">Tệp</a><a class="btn btn-secondary" href="<?=tms_url('/websites/logs',['name'=>$site['name']])?>">Logs</a></div>
<div class="site-control-grid"><form method="post" action="/websites/action"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($site['name'])?>"><?php if($status==='stopped'):?><button class="btn btn-primary btn-block" name="action" value="start">Bật website</button><?php else:?><div class="two-button"><button class="btn btn-secondary" name="action" value="restart">Nạp lại</button><button class="btn btn-danger-soft" name="action" value="stop">Dừng</button></div><?php endif;?></form><form method="post" action="/websites/snapshot"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($site['name'])?>"><button class="btn btn-secondary btn-block">Tạo snapshot</button></form></div>
<form method="post" action="/websites/update" class="inline-port-form"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($site['name'])?>"><input name="port" type="number" min="1024" max="65535" value="<?= (int)$site['port']?>"><button class="btn btn-secondary">Đổi cổng</button></form>
<form method="post" action="/websites/delete" class="delete-site-form" data-confirm="TMS OS sẽ tạo snapshot trước khi xóa website này. Tiếp tục?"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($site['name'])?>"><label class="check-line"><input type="checkbox" name="delete_files" value="1"><span>Xóa toàn bộ source website</span></label><button class="btn btn-danger-soft">Xóa website</button></form>
</article><?php endforeach;?>
</section>
<dialog id="create-site" class="tms-dialog"><form method="post" action="/websites/create" class="form-stack"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><div class="dialog-head"><h2>Tạo website</h2><button type="button" data-dialog-close>×</button></div><label>Tên website<input name="name" required pattern="[A-Za-z0-9_-]{2,40}" placeholder="demo"></label><label>Cổng<input name="port" required type="number" min="1024" max="65535" placeholder="8082"></label><button class="btn btn-primary">Tạo và kiểm tra</button></form></dialog>
<dialog id="clone-site" class="tms-dialog"><form method="post" action="/websites/clone" class="form-stack"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><div class="dialog-head"><h2>Nhân bản website</h2><button type="button" data-dialog-close>×</button></div><label>Website nguồn<select name="source" required><?php foreach($sites as $site):?><option value="<?=tms_h($site['name'])?>"><?=tms_h($site['name'])?></option><?php endforeach;?></select></label><label>Tên website mới<input name="name" required pattern="[A-Za-z0-9_-]{2,40}"></label><label>Cổng mới<input name="port" required type="number" min="1024" max="65535"></label><button class="btn btn-primary">Nhân bản an toàn</button></form></dialog>
<?php require dirname(__DIR__).'/layouts/footer.php';?>
