<?php $title='TMS Guardian · TMS OS';$showShell=true;$status=$data['status'];$config=$data['config'];require dirname(__DIR__).'/layouts/header.php';?>
<div class="page-head"><div><p class="eyebrow">TMS OS V14 · UNIFIED SELF-HEALING</p><h1>TMS Guardian</h1><p>Giám sát nhiều tầng, phát hiện upstream bị treo và tự phục hồi các dịch vụ cốt lõi.</p></div><span class="status-pill <?=$data['running']?'running':''?>" data-guardian-running><?=$data['running']?'Guardian đang chạy':'Guardian đã dừng'?></span></div>
<?php if(!empty($flash)):?><div class="alert <?=($flash['type']??'')==='success'?'alert-success':'alert-error'?>"><pre class="flash-pre"><?=tms_h($flash['message']??'')?></pre></div><?php endif;?>
<div class="guardian-summary" data-guardian-root>
<article class="panel-card guardian-health-card"><span>Panel 8888</span><strong data-guardian-value="panel"><?=tms_h((string)$status['panel'])?></strong><small><?=in_array((string)$status['panel'],['502','504','000'],true)?'Không khỏe':'Phản hồi bình thường'?></small></article>
<article class="panel-card guardian-health-card"><span>Website 8080</span><strong data-guardian-value="website"><?=tms_h((string)$status['website'])?></strong><small><?=in_array((string)$status['website'],['502','504','000'],true)?'Không khỏe':'Phản hồi bình thường'?></small></article>
<article class="panel-card guardian-health-card"><span>PHP Engine</span><strong data-guardian-bool="php"><?=!empty($status['php'])?'Khỏe':'Lỗi'?></strong><small>Unified Core + HTTP upstream</small></article>
<article class="panel-card guardian-health-card"><span>MariaDB</span><strong data-guardian-bool="mariadb"><?=!empty($status['mariadb'])?'Khỏe':'Dừng'?></strong><small>Unified Core + database readiness</small></article>
</div>
<div class="two-column-grid guardian-layout">
<section class="panel-card"><div class="section-title-row"><h2>Điều khiển Guardian</h2><small>PID: <?=tms_h($data['pid']?:'—')?></small></div><div class="service-actions guardian-actions">
<?php foreach(['start'=>'Khởi động','restart'=>'Khởi động lại','check'=>'Kiểm tra ngay','repair-php'=>'Sửa PHP','stop'=>'Dừng'] as $action=>$label):?><form method="post" action="/guardian/action"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="action" value="<?=$action?>"><button class="btn <?=$action==='stop'?'btn-danger-soft':($action==='repair-php'?'btn-primary':'btn-secondary')?>"><?=$label?></button></form><?php endforeach;?></div><p class="muted">Số lần sửa trong 1 giờ: <strong data-guardian-repair-count><?=$data['repair_count_hour']?></strong> / <?=$config['MAX_REPAIRS_PER_HOUR']?></p></section>
<section class="panel-card"><h2>Cấu hình tự phục hồi</h2><form method="post" action="/guardian/settings" class="form-grid"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><label class="toggle-row"><input type="checkbox" name="enabled" value="1" <?=$config['ENABLED']?'checked':''?>><span>Bật Guardian khi khởi động TMS OS</span></label><label class="toggle-row"><input type="checkbox" name="auto_repair" value="1" <?=$config['AUTO_REPAIR']?'checked':''?>><span>Tự sửa khi phát hiện lỗi</span></label><label class="toggle-row"><input type="checkbox" name="check_panel" value="1" <?=$config['CHECK_PANEL']?'checked':''?>><span>Kiểm tra Panel 8888</span></label><label class="toggle-row"><input type="checkbox" name="check_website" value="1" <?=$config['CHECK_WEBSITE']?'checked':''?>><span>Kiểm tra Website 8080</span></label><label class="toggle-row"><input type="checkbox" name="check_database" value="1" <?=$config['CHECK_DATABASE']?'checked':''?>><span>Kiểm tra MariaDB</span></label><label>Chu kỳ kiểm tra (giây)<input type="number" name="interval" min="15" max="300" value="<?=$config['INTERVAL']?>"></label><label>Giới hạn sửa mỗi giờ<input type="number" name="max_repairs" min="1" max="20" value="<?=$config['MAX_REPAIRS_PER_HOUR']?>"></label><button class="btn btn-primary">Lưu cấu hình</button></form></section>
</div>
<section class="panel-card"><div class="section-title-row"><h2>Nhật ký sự kiện và sửa chữa</h2><small data-guardian-updated>Cập nhật: <?=tms_h((string)($status['updated_at']?:'Chưa có'))?></small></div><div class="guardian-events" data-guardian-events><?php if(!$data['events']):?><p class="muted">Chưa có sự kiện Guardian.</p><?php endif;?><?php foreach($data['events'] as $event):?><div class="guardian-event guardian-<?=tms_h((string)($event['level']??'info'))?>"><span><?=tms_h(date('H:i:s d/m',strtotime((string)$event['time'])))?></span><strong><?=tms_h(strtoupper((string)$event['service']))?></strong><p><?=tms_h((string)$event['message'])?></p></div><?php endforeach;?></div></section>
<section class="panel-card"><h2>Cơ chế bảo vệ</h2><p>Guardian có khóa chống chạy trùng, giới hạn số lần tự sửa trong một giờ và chỉ thao tác trên các dịch vụ cố định. Với PHP-FPM, hệ thống kiểm tra phản hồi HTTP thật thay vì chỉ nhìn PID.</p></section>
<?php require dirname(__DIR__).'/layouts/footer.php';?>
