#!/data/data/com.termux/files/usr/bin/bash
# ============================================================
# tms-boot.sh — Quản lý auto-start TMS OS khi khởi động máy
# Termux dùng cơ chế ~/.termux/boot/ để tự chạy khi máy bật.
# Yêu cầu app Termux:Boot được cài (tự cài nếu chưa có).
#
# Cách dùng:
#   bash ~/tms-os/scripts/tms-boot.sh on    # Bật auto-start
#   bash ~/tms-os/scripts/tms-boot.sh off   # Tắt auto-start
#   bash ~/tms-os/scripts/tms-boot.sh status # Xem trạng thái
# ============================================================
set -uo pipefail
HOME="${HOME:-/data/data/com.termux/files/home}"
BOOT_DIR="$HOME/.termux/boot"
BOOT_FILE="$BOOT_DIR/tms-os.sh"
START_SCRIPT="$HOME/tms-os/scripts/start-tms.sh"

usage() {
  echo "Cách dùng: bash ~/tms-os/scripts/tms-boot.sh [on|off|status]"
  echo "  on     — Bật tự khởi động TMS OS khi máy bật"
  echo "  off    — Tắt tự khởi động"
  echo "  status — Xem trạng thái hiện tại"
}

case "${1:-status}" in
  on)
    if [ ! -f "$START_SCRIPT" ]; then
      echo "[LỖI] Không tìm thấy $START_SCRIPT — TMS OS chưa được cài."
      exit 1
    fi
    mkdir -p "$BOOT_DIR"
    cat > "$BOOT_FILE" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by TMS OS tms-boot.sh — tự khởi động server khi máy bật
export HOME="$HOME"
export PREFIX="$PREFIX"
# Chờ đủ thời gian cho Termux + mạng sẵn sàng sau khi boot
sleep 10
if [ -f "$START_SCRIPT" ]; then
  bash "$START_SCRIPT" >> "$HOME/logs/services/boot.log" 2>&1
fi
EOF
    chmod 700 "$BOOT_FILE"
    # Cài app Termux:Boot nếu chưa có (mở trang cài)
    if ! pm list packages com.termux.boot >/dev/null 2>&1; then
      echo "[INFO] Chưa có app Termux:Boot. Mở trang cài đặt..."
      (termux-open "https://f-droid.org/packages/com.termux.boot/" >/dev/null 2>&1) &
    fi
    echo "[OK] Đã BẬT auto-start TMS OS."
    echo "  Lưu ý: mở app Termux:Boot 1 lần sau khi cài để kích hoạt."
    ;;
  off)
    rm -f "$BOOT_FILE"
    echo "[OK] Đã TẮT auto-start TMS OS."
    ;;
  status)
    if [ -f "$BOOT_FILE" ]; then
      echo "Auto-start: BẬT"
      echo "  File: $BOOT_FILE"
      echo "  Khi máy bật, TMS OS sẽ tự chạy: bash ~/tms-os/scripts/start-tms.sh"
      if ! pm list packages com.termux.boot >/dev/null 2>&1; then
        echo "  ⚠ Chưa cài app Termux:Boot — hãy cài để auto-start hoạt động:"
        echo "    termux-open https://f-droid.org/packages/com.termux.boot/"
      fi
    else
      echo "Auto-start: TẮT"
      echo "  Bật bằng: bash ~/tms-os/scripts/tms-boot.sh on"
    fi
    ;;
  *)
    usage; exit 1 ;;
esac
