<?php $title='App Installer · TMS OS';$showShell=true;require dirname(__DIR__).'/layouts/header.php';?>
<div class="page-head"><div><p class="eyebrow">ONE-CLICK DEPLOY</p><h1>App Installer</h1><p>Triển khai ứng dụng vào website riêng, kiểm tra kết nối và tự rollback khi lỗi.</p></div></div>
<?php if(!empty($flash)):?><div class="alert <?=($flash['type']??'')==='success'?'alert-success':'alert-error'?>" data-flash-toast="<?=($flash['type']??'')==='success'?'success':'error'?>" hidden><pre class="flash-pre"><?=tms_h($flash['message']??'')?></pre></div><?php endif;?>
<div class="plugin-grid"><?php foreach($catalog as $app):?>
<article class="panel-card plugin-card"><div class="plugin-icon"><?=tms_h(strtoupper(substr($app['name'],0,2)))?></div><h2><?=tms_h($app['name'])?></h2><p><?=tms_h($app['description'])?></p><small><?=tms_h($app['requirements'])?></small><button class="btn btn-primary btn-block" data-app-select="<?=tms_h($app['id'])?>" data-app-db="<?=$app['database']?'1':'0'?>">Cài đặt</button></article>
<?php endforeach;?></div>
<section class="panel-card"><h2>Ứng dụng đã cài</h2>
<?php if(empty($installed)):?><p>Chưa có ứng dụng nào.</p><?php else:?><div class="table-wrap"><table><thead><tr><th>Tên</th><th>Loại</th><th>Cổng</th><th>Trạng thái</th><th>Ngày cài</th></tr></thead><tbody><?php foreach($installed as $app):?><tr><td><?=tms_h($app['name'])?></td><td><?=tms_h($app['app'])?></td><td><?= (int)$app['port']?></td><td><span class="status-pill running"><?=tms_h($app['health']??'ready')?></span></td><td><?=tms_h($app['installed_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<dialog id="install-app-dialog" class="tms-dialog"><form method="post" action="/apps/install" class="form-stack"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="app" id="selected-app"><div class="dialog-head"><h2>Cài ứng dụng</h2><button type="button" data-dialog-close>×</button></div>
<label>Tên website<input name="name" required pattern="[A-Za-z0-9_-]{2,40}" placeholder="myapp"></label><label>Cổng<input name="port" type="number" min="1024" max="65535" required placeholder="8090"></label>
<div id="database-fields" hidden><label>Database<input name="db_name" placeholder="myapp_db"></label><label>Database user<input name="db_user" placeholder="myapp_user"></label><label>Mật khẩu database<input name="db_pass" type="password" minlength="8"></label>
<div class="wp-auto-box"><label class="check-line"><input type="checkbox" name="wp_auto_setup" value="1" checked data-wp-auto> Cấu hình WordPress tự động</label><div data-wp-fields><label>Tiêu đề website<input name="wp_site_title" placeholder="Website của tôi"></label><label>Tài khoản quản trị<input name="wp_admin_user" value="admin" pattern="[A-Za-z0-9_.@-]{3,40}"></label><label>Mật khẩu quản trị<input name="wp_admin_pass" type="password" minlength="10" placeholder="Để trống để TMS OS tự tạo"></label><label>Email quản trị<input name="wp_admin_email" type="email" placeholder="admin@example.com"></label><label>Ngôn ngữ<select name="wp_language"><option value="vi">Tiếng Việt</option><option value="en_US">English</option></select></label></div></div>
</div><button class="btn btn-primary">Cài đặt ngay</button></form></dialog>
<?php require dirname(__DIR__).'/layouts/footer.php';?>
