<?php $title='Database · TMS OS';$showShell=true;require dirname(__DIR__).'/layouts/header.php';?>
<div class="page-head"><div><p class="eyebrow">Database Manager · <?=tms_h(($driver ?? 'MariaDB'))?></p><h1>Database</h1></div><?php if($driver==='SQLite'):?><button class="btn btn-primary" data-modal-open="db-modal">+ Tạo database</button><?php endif;?></div><?php if($flash):?><div class="alert <?=$flash['type']==='success'?'alert-success':'alert-error'?>"><?=nl2br(tms_h((string)$flash['message']))?></div><?php endif;?><?php if($error):?><div class="alert alert-error"><?=tms_h($error)?></div><?php endif;?><?php
$managed=[];$website=[];
foreach($databases as $d){if(($d['source'] ?? 'managed')==='website'){$website[]=$d;}else{$managed[]=$d;}}
?><?php if($driver==='SQLite'):?><div class="db-groups">
<section class="table-card"><div class="simple-table head"><span>Database TMS OS</span><span>Thao tác</span></div><?php foreach($managed as $db):?><?php $size=tms_format_bytes($db['size'] ?? 0);?>
<div class="simple-table"><div><strong><?=tms_h($db['name'])?></strong><br><span class="muted" style="font-size:.8em"><?=tms_h($size)?></span></div><div class="table-actions"><form method="post" action="/databases/export"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><button class="btn btn-secondary">Xuất SQL</button></form><form method="post" action="/databases/import" enctype="multipart/form-data" class="import-form"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><label class="btn btn-secondary"><input type="file" name="sql" accept=".sql" hidden required>Nhập SQL</label><button class="btn btn-secondary">Chạy</button></form><form method="post" action="/databases/drop" data-confirm="Xóa database <?=tms_h($db['name'])?>?"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><button class="btn btn-danger-soft">Xóa</button></form></div></div><?php endforeach;?><?php if(!$managed):?><div class="empty-state">Chưa có database TMS OS. Bấm "+ Tạo database" để tạo.</div><?php endif;?></section>
<section class="table-card"><div class="simple-table head"><span>Database trong website <span class="muted" style="font-weight:400;font-size:.85em">(Typecho, ứng dụng người dùng)</span></span><span>Thao tác</span></div><?php foreach($website as $db):?><?php $size=tms_format_bytes($db['size'] ?? 0);?>
<div class="simple-table"><div><strong><?=tms_h($db['name'])?> <span style="display:inline-flex;align-items:center;gap:6px;padding:2px 10px;border-radius:999px;background:rgba(var(--primary-rgb),.12);color:var(--primary);font-weight:800;font-size:.72rem" title="Website: <?=tms_h($db['site'])?>"><?=tms_h($db['site'])?></span></strong><br><span class="muted" style="font-size:.8em"><?=tms_h($db['size'] ? $size . ' · ' . tms_h(str_replace((getenv('HOME') ?: '/data/data/com.termux/files/home') . '/', '', $db['path'])) : $size)?></span></div><div class="table-actions"><form method="post" action="/databases/export"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="path" value="<?=tms_h($db['path'])?>"><button class="btn btn-secondary">Xuất SQL</button></form><form method="post" action="/databases/adopt" data-confirm="Mang database này về thư mục quản lý của TMS OS? File gốc trong website vẫn được giữ nguyên."><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="path" value="<?=tms_h($db['path'])?>"><button class="btn btn-secondary">Mang về quản lý</button></form></div></div><?php endforeach;?><?php if(!$website):?><div class="empty-state">Chưa tìm thấy file database trong các website. Hệ thống tự động phát hiện file SQLite (*.sqlite3, *.sqlite, *.db) trong thư mục website.</div><?php endif;?></section>
</div><?php else:?><section class="table-card"><div class="simple-table head"><span>Tên database</span><span>Thao tác</span></div><?php foreach($databases as $db):?><div class="simple-table"><strong><?=tms_h($db['name'])?></strong><div class="table-actions"><form method="post" action="/databases/export"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><button class="btn btn-secondary">Xuất SQL</button></form><form method="post" action="/databases/import" enctype="multipart/form-data" class="import-form"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><label class="btn btn-secondary"><input type="file" name="sql" accept=".sql" hidden required>Nhập SQL</label><button class="btn btn-secondary">Chạy</button></form><form method="post" action="/databases/drop" data-confirm="Xóa database <?=tms_h($db['name'])?>?"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><input type="hidden" name="name" value="<?=tms_h($db['name'])?>"><button class="btn btn-danger-soft">Xóa</button></form></div></div><?php endforeach;?><?php if(!$databases):?><div class="empty-state">Chưa có database người dùng.</div><?php endif;?></section><?php endif;?>
<div class="modal" id="db-modal"><div class="modal-card"><button class="modal-close" data-modal-close>×</button><h2>Tạo database</h2><form method="post" action="/databases/create" class="stack"><input type="hidden" name="csrf" value="<?=tms_h($csrf)?>"><label><span>Tên database</span><input name="name" placeholder="project_db" required></label><button class="btn btn-primary">Tạo database</button></form></div></div><?php require dirname(__DIR__).'/layouts/footer.php';?>
