<?php
declare(strict_types=1);
final class FileManagerController
{
    public function __construct(private AuthService $auth,private FileManagerService $files){}
    private function guard(): void { if(!$this->auth->check())tms_redirect('/login'); }
    public function index(): void { $this->guard();$root=(string)($_GET['root']??'websites');$path=(string)($_GET['path']??'');$q=trim((string)($_GET['q']??''));try{$listing=$this->files->browse($root,$path);if($q!=='')$listing['items']=$this->files->search($root,$path,$q);tms_view('files.index',['listing'=>$listing,'roots'=>$this->files->roots(),'query'=>$q,'flash'=>tms_pull_flash(),'csrf'=>tms_csrf_token()]);}catch(Throwable $e){tms_flash('error',$e->getMessage());tms_redirect('/files');}}
    public function editor(): void { $this->guard();$root=(string)($_GET['root']??'websites');$file=(string)($_GET['file']??'');try{$doc=$this->files->read($root,$file);tms_view('files.editor',['document'=>$doc,'root'=>$root,'csrf'=>tms_csrf_token(),'flash'=>tms_pull_flash()]);}catch(Throwable $e){tms_flash('error',$e->getMessage());tms_redirect('/files');}}
    public function upload(): void { $this->mutate(function(){ $r=(string)($_POST['root']??'websites');$p=(string)($_POST['path']??'');$n=$this->files->upload($r,$p,$_FILES['upload']??[]);return ['Đã tải lên: '.$n,$r,$p];}); }
    public function create(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$p=(string)$_POST['path'];$this->files->create($r,$p,(string)$_POST['name'],(string)($_POST['kind']??'file')==='folder');return ['Đã tạo thành công.',$r,$p];}); }
    public function rename(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$rel=(string)$_POST['relative'];$this->files->rename($r,$rel,(string)$_POST['new_name']);return ['Đã đổi tên.',$r,dirname($rel)==='.'?'':dirname($rel)];}); }
    public function delete(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$rel=(string)$_POST['relative'];$this->files->delete($r,$rel);return ['Đã xóa.',$r,dirname($rel)==='.'?'':dirname($rel)];}); }
    public function archive(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$rel=(string)$_POST['relative'];$n=$this->files->archive($r,$rel);return ['Đã tạo '.$n,$r,dirname($rel)==='.'?'':dirname($rel)];}); }
    public function extract(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$rel=(string)$_POST['relative'];$this->files->extract($r,$rel);return ['Đã giải nén.',$r,dirname($rel)==='.'?'':dirname($rel)];}); }
    public function chmod(): void { $this->mutate(function(){ $r=(string)$_POST['root'];$rel=(string)$_POST['relative'];$this->files->chmod($r,$rel,(string)$_POST['mode']);return ['Đã cập nhật quyền.',$r,dirname($rel)==='.'?'':dirname($rel)];}); }
    public function save(): void { $this->guard();if(!tms_verify_csrf($_POST['csrf']??null)){tms_flash('error','Phiên không hợp lệ.');tms_redirect('/files');}$r=(string)$_POST['root'];$f=(string)$_POST['file'];try{$this->files->save($r,$f,(string)($_POST['content']??''));tms_flash('success','Đã lưu tệp.');}catch(Throwable $e){tms_flash('error',$e->getMessage());}tms_redirect(tms_url('/files/editor',['root'=>$r,'file'=>$f])); }
    public function download(): void { $this->guard();try{$d=$this->files->download((string)($_GET['root']??'websites'),(string)($_GET['file']??''));header('Content-Type: '.$d['mime']);header('Content-Length: '.$d['size']);header('Content-Disposition: attachment; filename="'.rawurlencode($d['name']).'"');readfile($d['path']);exit;}catch(Throwable $e){tms_flash('error',$e->getMessage());tms_redirect('/files');}}
    private function mutate(callable $cb): void { $this->guard();if(!tms_verify_csrf($_POST['csrf']??null)){tms_flash('error','Phiên không hợp lệ.');tms_redirect('/files');}try{[$m,$r,$p]=$cb();tms_flash('success',$m);}catch(Throwable $e){$r=(string)($_POST['root']??'websites');$p=(string)($_POST['path']??'');tms_flash('error',$e->getMessage());}tms_redirect(tms_url('/files',['root'=>$r,'path'=>$p])); }
}
