<?php
$ui=tms_ui_settings();
$theme=$_COOKIE['tms_theme']??$ui['default_theme'];
$current=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
if(!function_exists('nav_active')){function nav_active(string $prefix,string $current):string{return $prefix==='/'?($current==='/'?'active':''):(str_starts_with($current,$prefix)?'active':'');}}
?>
<link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" as="style">
<!doctype html><html lang="vi" data-theme="<?=tms_h($theme)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="<?=tms_h($ui['accent'])?>"><meta name="application-name" content="TMS OS"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="manifest" href="/tms-pwa-v21.json?v=<?=tms_asset_version()?>"><link rel="apple-touch-icon" href="<?=tms_h(tms_brand_icon('192'))?>"><link rel="icon" href="/assets/favicon.png"><meta name="csrf-token" content="<?=tms_h(tms_csrf_token())?>"><title><?=tms_h($title??tms_config('name'))?></title><style>:root{--primary:<?=tms_h($ui['accent'])?>;--primary2:<?=tms_h($ui['accent_secondary'])?>;--primary-rgb:<?=tms_h(tms_hex_rgb($ui['accent']))?>}</style><link rel="stylesheet" href="/assets/app.css?v=<?=tms_asset_version()?>"><script defer src="/assets/app.js?v=<?=tms_asset_version()?>" data-toast-duration="<?=tms_h($ui['toast_duration']??5)?>"></script></head><body>
<?php if(!empty($showShell)):?><div class="os-shell"><aside class="os-sidebar" id="sidebar"><div class="os-brand"><img class="brand-logo small" src="<?=tms_h(tms_brand_icon('logo'))?>" alt="TMS OS"><div><strong>TMS OS</strong></div></div><nav class="os-nav os-nav-grid">
<a class="nav-item <?=nav_active('/dashboard',$current)?>" href="/dashboard"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="9" rx="1.5"/><rect x="14" y="3" width="7" height="5" rx="1.5"/><rect x="14" y="12" width="7" height="9" rx="1.5"/><rect x="3" y="16" width="7" height="5" rx="1.5"/></svg></span>Dashboard</a>
<a class="nav-item <?=nav_active('/files',$current)?>" href="/files"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7V5a1 1 0 0 1 1-1h4l1.6 2H19a1 1 0 0 1 1 1v11a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7Z"/></svg></span>File Manager</a>
<a class="nav-item <?=nav_active('/websites',$current)?>" href="/websites"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="3.6" ry="9"/><path d="M3.2 8.5h17.6M3.2 15.5h17.6"/></svg></span>Website</a>
<a class="nav-item <?=nav_active('/databases',$current)?>" href="/databases"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5"/><path d="M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/></svg></span>Database</a>
<a class="nav-item <?=nav_active('/cron',$current)?>" href="/cron"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg></span>Cron Jobs</a>
<a class="nav-item <?=nav_active('/network',$current)?>" href="/network"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12.55a11 11 0 0 1 14 0"/><path d="M8.5 16.43a6 6 0 0 1 7 0"/><circle cx="12" cy="20" r="1" fill="currentColor" stroke="none"/><path d="M1.5 8.7a16 16 0 0 1 21 0"/></svg></span>Network Center</a>
<a class="nav-item <?=nav_active('/terminal',$current)?>" href="/terminal"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m4 17 6-5-6-5"/><path d="M12 19h8"/></svg></span>Terminal</a>
<a class="nav-item <?=nav_active('/services',$current)?>" href="/services"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M12 2v4M12 18v4M2 12h4M18 12h4M4.9 4.9l2.8 2.8M16.3 16.3l2.8 2.8M4.9 19.1l2.8-2.8M16.3 7.7l2.8-2.8"/></svg></span>Service Manager</a>
<a class="nav-item <?=nav_active('/guardian',$current)?>" href="/guardian"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2.5 4.5 5.6v5.9c0 5.1 3.2 8.6 7.5 9.9 4.3-1.3 7.5-4.8 7.5-9.9V5.6L12 2.5Z"/><path d="m9.5 12.2 2 2 3.5-4"/></svg></span>Guardian</a>
<a class="nav-item <?=nav_active('/cf-hosting',$current)?>" href="/cf-hosting"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6.5 18a4.5 4.5 0 0 1 .4-8.97A7 7 0 0 1 20.4 9.6 4 4 0 0 1 20 18H6.5Z"/></svg></span>Cloudflare Hosting</a>
<a class="nav-item <?=nav_active('/modules',$current)?>" href="/modules"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 20 8v8l-8 5-8-5V8l8-5Z"/><path d="M12 12 4 7.5M12 12v8.5M12 12l8-4.5"/></svg></span>Module Center</a>
<a class="nav-item <?=nav_active('/packages',$current)?>" href="/packages"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg></span>Runtime Packages</a>
<a class="nav-item <?=nav_active('/monitoring',$current)?>" href="/monitoring"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 12h4l2-6 4 12 2-6h6"/></svg></span>Resource Monitor</a>
<a class="nav-item <?=nav_active('/notifications',$current)?>" href="/notifications"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9Z"/><path d="M10.3 20.5a2 2 0 0 0 3.4 0"/></svg></span>Thông báo</a>
<a class="nav-item <?=nav_active('/updates',$current)?>" href="/updates"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 1 1-2.6-6.4"/><path d="M21 3v6h-6"/></svg></span>Update Center</a>
<a class="nav-item <?=nav_active('/backups',$current)?>" href="/backups"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v12"/><path d="m7 10 5 5 5-5"/><path d="M5 21h14"/></svg></span>Backup</a>
<a class="nav-item <?=nav_active('/logs',$current)?>" href="/logs"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16v16H4z"/><path d="M8 8h8M8 12h8M8 16h5"/></svg></span>Logs</a>
<div class="nav-divider" aria-hidden="true"></div>
<a class="nav-item <?=nav_active('/diagnostics',$current)?>" href="/diagnostics"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg></span>System Check</a>
<a class="nav-item nav-settings <?=nav_active('/settings',$current)?>" href="/settings"><span><svg viewBox="0 0 24 24" fill="none" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.8l.1.1a2 2 0 1 1-2.8 2.8l-.1-.1a1.7 1.7 0 0 0-1.8-.3 1.7 1.7 0 0 0-1 1.5V21a2 2 0 1 1-4 0v-.1a1.7 1.7 0 0 0-1.1-1.5 1.7 1.7 0 0 0-1.8.3l-.1.1a2 2 0 1 1-2.8-2.8l.1.1a1.7 1.7 0 0 0 .3-1.8 1.7 1.7 0 0 0-1.5-1H3a2 2 0 1 1 0-4h.1a1.7 1.7 0 0 0 1.5-1.1 1.7 1.7 0 0 0-.3-1.8l-.1-.1a2 2 0 1 1 2.8-2.8l.1.1a1.7 1.7 0 0 0-.3 1.8v0a1.7 1.7 0 0 0 1.5 1H21a2 2 0 1 1 0 4h-.1a1.7 1.7 0 0 0-1.5 1Z"/></svg></span>Cài đặt</a>
</nav><div class="sidebar-footer"><button type="button" class="btn btn-primary btn-block pwa-install-hidden" data-pwa-install>⤓ Cài TMS OS lên màn hình chính</button><button type="button" class="btn btn-ghost btn-block" data-theme-toggle>Đổi giao diện</button><form method="post" action="/logout"><input type="hidden" name="csrf" value="<?=tms_h(tms_csrf_token())?>"><button class="btn btn-danger-soft btn-block">Đăng xuất</button></form></div></aside><div class="sidebar-overlay" data-sidebar-overlay></div><main class="os-main"><header class="mobile-header"><button class="menu-button" data-menu-toggle>☰</button><strong>TMS OS</strong><span class="online-dot"></span></header><?php endif;?>
